config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'about' => 'welcome#about'
  get 'team' => 'welcome#team'
  get 'service' => 'welcome#service'
  get 'classiccase' => 'welcome#classiccase'
  get 'contact' => 'welcome#contact'
  get 'dynamic' => 'welcome#dynamic'

  resources :cases, :only => [:index, :show]
  resources :news, :only => [:index, :show]
  resources :members, :only => [:index, :show]

  namespace :admin do
    root 'welcome#index'
    resources :columns do
      resources :articles
    end
    resources :news do
      resources :sections
    end
    resources :cases
    resources :members
  end

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :author, type: String, default: ''
  field :index, type: Integer, default: 1

  field :html_content, type: String, default: ''

  belongs_to :column


  validates :title, presence: true

end

app/models/column.rb
class Column
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :level, type: Integer, default: 1
  field :index, type: Integer, default: 1

  field :html_content, type: String, default: ''

  has_many :columns
  belongs_to :column


  validates :name, presence: true, uniqueness: true

  scope :top, ->{where(:level => 1)}

end

app/models/member.rb
class Member
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :title, type: String, default: ''
  field :position, type: String, default: ''
  field :index, type: Integer, default: 1
  field :level, type: Integer, default: 1

  field :html_content, type: String, default: ''

	mount_uploader :avatar, AvatarUploader

  field :html_content, type: String, default: ''

  validates :name, presence: true


end

app/controllers/admin/articles_controller.rb
module Admin
	class ArticlesController < BaseController
		def index
			@column = Column.find(params[:column_id])
			@articles = Article.where(:column_id => @column.id).desc(:created_at)
		end

		def new
			@column = Column.find(params[:column_id])
			@article = Article.new
			@article.html_content = @column.html_content
		end

		def create
			@column = Column.find(params[:column_id])
			@article = Article.create!(params.require(:article).permit(:title, :author, :index, :html_content)) do |article|
				article.column_id = @column.id
			end
			redirect_to admin_column_articles_path(@column)
		end

		def edit
			@column = Column.find(params[:column_id])
			@article = Article.find(params[:id])
		end

		def update
			@column = Column.find(params[:column_id])
			@article = Article.find(params[:id])
			@article.update_attributes(params.require(:article).permit(:title, :author, :index, :html_content))
			redirect_to admin_column_articles_path(@column)
		end

		def destroy
			@column = Column.find(params[:column_id])
			@article = Article.find(params[:id])
			@article.destroy
			redirect_to admin_column_articles_path(@column)
		end
	end
end

app/controllers/admin/base_controller.rb
module Admin
	class BaseController < ActionController::Base
	  # before_filter :authorize_login
	  http_basic_authenticate_with name: "guanfu", password: "guanfulaw"
	  layout 'admin'

	  def current_user
	  	# User.find(session[:current_user_id]) if session[:current_user_id]
	  end

	  protected
	  def authorize_login
	  	return render :json => '请登录！', :status => 401 if current_user.nil?
	  end

	end
end

app/controllers/admin/columns_controller.rb
module Admin
	class ColumnsController < BaseController
		def index
			@columns = Column.all
		end

		def new
			@column = Column.new
		end

		def create
			@column = Column.create(params.require(:column).permit(:name, :index, :level, :column_id, :html_content))
			redirect_to admin_columns_path
		end

		def edit
			@column = Column.find(params[:id])
		end

		def update
			@column = Column.find(params[:id])
			@column.update_attributes(params.require(:column).permit(:name, :index, :level, :column_id, :html_content))
			redirect_to admin_columns_path
		end

		def destroy
			@column = Column.find(params[:id])
			@column.destroy
		end
	end
end

app/controllers/admin/members_controller.rb
module Admin
	class MembersController < BaseController
		def index
			@members = Member.all
		end

		def new
			@member = Member.new
		end

		def create
			@member = Member.create!(params.require(:member).permit(:title, :name, :position, :level, :avatar, :avatar_cache, :html_content))
			redirect_to admin_members_path
		end

		def edit
			@member = Member.find(params[:id])
		end

		def update
			@member = Member.find(params[:id])
			@member.update_attributes(params.require(:member).permit(:title, :name, :position, :level, :avatar, :avatar_cache, :html_content))
			redirect_to admin_members_path
		end

		def destroy
			@member = Member.find(params[:id])
			@member.destroy
			redirect_to admin_members_path
		end
	end
end

app/controllers/admin/welcome_controller.rb
module Admin
	class WelcomeController < BaseController
		def index
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
	def index
		cases_column = Column.where(:name => '案例').first
		@cases = Article.where(:column_id => cases_column.id).desc(:created_at).limit(5)
		@path_action = 'cases'
	end

	def show
		@case = Article.find(params[:id])
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	def show
		@member = Member.find(params[:id])
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def index
		news_column = Column.where(:name => '动态').first
		@newes = Article.where(:column_id => news_column.id).desc(:created_at).limit(5)
	end

	def show
		@news = Article.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		news_column = Column.where(:name => '动态').first
		@newes = Article.where(:column_id => news_column.id).desc(:created_at).limit(5)

		cases_column = Column.where(:name => '案例').first
		@cases = Article.where(:column_id => cases_column.id).desc(:created_at).limit(5)

		@path_action = 'root'
	end

	def about
		@path_action = 'about'
	end

	def team
		@path_action = 'team'
	end

	def service
		@path_action = 'service'
	end

	def classiccase
		@path_action = 'cases'
	end

	def contact
		@path_action = 'contact'
	end

	def dynamic
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.html.erb
<div style="display: inline-block; min-height: 500px;">
<%= form_for([:admin, @column, @article]) do |f| %>
    标题：<%= f.text_field(:title) %><br/>
    作者：<%= f.text_field(:author) %><br/>
    位置：<%= f.text_field(:index) %><br/>

    内容:
    <%= f.text_area :html_content, rows: 60 %>

    <%= f.submit '确定' %>
<% end %>
</div>

<script type="text/javascript">
    var csrfitems = document.getElementsByName("csrfmiddlewaretoken");
    var csrftoken = "";
    if(csrfitems.length > 0)
    {
        csrftoken = csrfitems[0].value;
    }
         
    var editor ;
    KindEditor.ready(function(K) {  
        var options = {  
            width : '360px',  
            height : '500px',  
            filterMode : true,
            uploadJson : K.undef('/kindeditor/upload/'),
            extraFileUploadParams : {
                csrfmiddlewaretoken:csrftoken
            }
       };  
        editor = K.create('textarea', options);  
    });                      
</script> 

app/views/admin/articles/edit.html.erb
<div style="font-size: 18px;">
	编辑栏目
</div>
<div style="font-size: 16px;">
	<%= render('form') %>
</div>

app/views/admin/articles/index.html.erb
<style type="text/css">
	table{
		background-color: black;
	}
	td{
		background-color: white;
		font-size: 16px;
	}
	thead td
	{
		font-size: 22px;
	}
</style>



<!--begin-->
<div style="display: inline-block; min-height: 400px;min-width: 640px;">
   		<a href="<%= new_admin_column_article_path(@column) %>" target="black" style="font-size: 18px;font-weight: bold;border: 1px solid;background: lightgoldenrodyellow;">新增文章</a>
<table style="font-size: 22px;margin-top: 10px;width:100%;text-align: center;" border="0" cellspacing="1" cellpadding="0">


	<thead>
		<tr>
			<td>标题</td>
			<td>作者</td>
			<td>位置</td>
			<td>操作</td>
		</tr>
	</thead>
	<tbody>
		<% @articles.each do |article| %>
			<tr>
				<td><%= article.title %></td>
				<td><%= article.author %></td>
				<td><%= article.index %></td>
				<td>
					<%= link_to '编辑', edit_admin_column_article_path(@column, article), target: 'black' %>
					<%= link_to '删除', admin_column_article_path(@column, article), method: 'delete', data: { confirm: '您确定删除这篇文章么？'} %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/admin/articles/new.html.erb
<div style="font-size: 18px;">
	新建文章
</div>
<div style="font-size: 16px;">
	<%= render('form') %>
</div>

app/views/admin/cases/_form.html.erb
<%= form_for([:admin, @case]) do |f| %>
	标题：<%= f.text_field(:title) %><br/>
	作者：<%= f.text_field(:author) %><br/>
	位置：<%= f.text_field(:index) %><br/>
	
	案情：<%= f.text_area(:an_qing) %><br>
	裁决：<%= f.text_area(:cai_jue) %><br/>
	评析：<%= f.text_area(:ping_xi) %><br/>


	<%= f.submit %>
<% end %>

app/views/admin/cases/index.html.erb
<%= link_to '新增案情', new_admin_case_path %>
<table>
	<thead>
		<tr>
			<td>标题</td>
			<td>作者</td>
			<td>位置</td>
			<td>操作</td>
		</tr>
	</thead>
	<tbody>
		<% @cases.each do |_case| %>
			<tr>
				<td><%= _case.title %></td>
				<td><%= _case.author %></td>
				<td><%= _case.index %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/cases/new.html.erb
<div>
	新建案例
</div>
<div>
	<%= render('form') %>
</div>

app/views/admin/columns/_form.html.erb
<%= form_for([:admin, @column]) do |f| %>
	名称：<%= f.text_field(:name) %><br/>
	位置：<%= f.text_field(:index) %><br/>

	父栏目：
	<%= f.select :column_id, Column.top.collect { |c| [ c.name, c.id ] }, include_blank: true %><br/>

	模板
    <div style="margin-left:31%;">
    <%= f.text_area :html_content %>
    </div>

	<%= f.submit '确定' %>
<% end %>

<script type="text/javascript">
    var csrfitems = document.getElementsByName("csrfmiddlewaretoken");
    var csrftoken = "";
    if(csrfitems.length > 0)
    {
        csrftoken = csrfitems[0].value;
    }
         
    var editor ;
    KindEditor.ready(function(K) {  
        var options = {  
            width : '360px',  
            height : '300px',  
            filterMode : true,
            uploadJson : K.undef('/kindeditor/upload/'),
            extraFileUploadParams : {
                csrfmiddlewaretoken:csrftoken
            }
       };  
        editor = K.create('textarea', options);  
    });                      
</script> 

app/views/admin/columns/edit.html.erb
<div style="font-size: 18px;">
	编辑栏目
</div>
<div style="font-size: 16px;">
	<%= render('form') %>
</div>

app/views/admin/columns/index.html.erb
<style type="text/css">
	table{
		background-color: black;
	}
	td{
		background-color: white;
	}
</style>

<% if false %>
<div>
	顶级栏目:
	<% Column.top.each do |column| %>
		<%= column.name %>
	<% end %>
</div>
<%= link_to '新增栏目', new_admin_column_path, :target => 'black' %>
<table>
	<thead>
		<tr>
			<td>名称</td>
			<td>层级</td>
			<td>位置</td>
			<td>操作</td>
		</tr>
	</thead>
	<tbody>
		<% @columns.each do |column| %>
			<tr>
				<td><%= column.name %></td>
				<td><%= column.level %></td>
				<td><%= column.index %></td>
				<td>
					<%= link_to '编辑', edit_admin_column_path(column), :target => 'black' %>
					<%= link_to '文章管理', admin_column_articles_path(column) %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<% end %>




<!--begin-->
<div style="display: inline-block;min-height: 400px;text-align: center;min-width: 640px;">
	<div style="font-size: 33px;font-weight: bold;">
		顶级栏目:
		动态
		案例
	</div>
	<a href="http://www.guanfulaw.com/admin/columns/new" target="black" style="font-size: 22px;display: inline-block;margin-top: 10px;width:100%;">新增顶级栏目</a>
	<table style="font-size: 22px;margin-top: 10px;width:100%;text-align: center;" border="0" cellspacing="1" cellpadding="0">
		<thead>
			<tr>
				<td>名称</td>
				<td>层级</td>
				<td>位置</td>
				<td>编辑</td>
				<td>管理</td>
			</tr>
		</thead>
		<tbody>
			<% @columns.each do |column| %>
				<tr>
					<td><%= column.name %></td>
					<td><%= column.level %></td>
					<td><%= column.index %></td>
					<td>
						<%= link_to '编辑', edit_admin_column_path(column), :target => 'black' %>
					</td>
					<td>
						<%= link_to '文章管理', admin_column_articles_path(column) %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<!-- end-->

app/views/admin/columns/new.html.erb
<div style="font-size: 18px;">
	新建栏目
</div>
<div style="font-size: 16px;">
	<%= render('form') %>
</div>

app/views/admin/sections/_form.html.erb
<%= form_for([:admin, @news]) do |f| %>

	标题：<%= f.text_field(:title) %><br/>

	<%= f.submit %>
<% end %>

app/views/admin/sections/index.html.erb
<%= link_to '新增内容', new_admin_news_section_path(@news) %>
<table>
	<thead>
		<tr>
			<td>标题</td>
			<td>操作</td>
		</tr>
	</thead>
	<tbody>
		<% @sections.each do |section| %>
			<tr>
				<td><%= news.desc[0..10] %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/sections/new.html.erb
<div>
	新建内容
</div>
<div>
	<%= render('form') %>
</div>

app/views/admin/welcome/index.html.erb
<!-- begin-->
<div style="display: inline-block; min-height: 400px;">

	<h1><span style="display: inline-block;font-size: 0.9em;">欢迎来到</span> <span style="display: inline-block;font-size: 1.3em;">观复律师网</span> <span style="display: inline-block;font-size: 0.9em;">管理系统</span></h1>
	<a href="<%= admin_columns_path %>" style="font-size: 22px;border: 1px solid gray;margin-top: 10px;padding: 10px;display: inline-block;">栏目管理</a><br>
	<br>
	<br>
	<a href="<%= admin_members_path %>" style="font-size: 22px;border: 1px solid gray;margin-top: 10px;padding: 10px;display: inline-block;">成员管理</a><br>
</div>
<!-- end-->

app/views/cases/_home_share_list.html.erb
<div class="classic-case-container">
  <div class="container-head">
     <span class="container-head-left">经典案例</span>
     <a href="/cases.html"><span class="container-head-right" id="gotoClassic">查看更多></span></a>
  </div>
  <div><%= image_tag('linksShadows.png') %></div>
  <div class="case-info">
     <div class="image-info">
     </div>
     <div class="case-list">
        <% @cases.each do |_case| %>
        <div class="case">
           <span class="case-title">
           <%= link_to _case.title, case_path(_case) %>
           </span>
           <span class="case-time"><%= _case.created_at.strftime('%Y-%m-%d') %></span>
        </div>
        <% end %>
     </div>

  </div>
</div>

app/views/cases/index.html.erb
<style type="text/css">

body
{
  text-align: center;
}
.gfclassiclist-container{
  width: 980px;
  min-height: 530px;
  margin: 30px auto;
  display: inline-block;
}
.gfclassiclist-left-container{
  width: 240px;
  height: 100%;
  float: left;
}
.gfclassiclist-right-container{
  width: 720px;
  height: 100%;
  margin-left: 20px;
  background-color: #f1f1f1;
  border-radius: 0 0 10px 10px;
  float: left;
}
.left-title{
  width: 100%;
  height: 40px;
  background-color: #00a0e9;
  color: #fff;
  line-height: 2;
}
.left-title span{
  display: inline-block;
}
.left-CN{
  font-size: 20px;
  padding-left: 20px;
}
.left-EN{
  font-size: 12px;
}
.gfclassiclist-info{
  width: 100%;
  height: 40px;
  text-align: center;
  font-size: 14px;
  color: #525252;
  line-height: 2.8;
  cursor: pointer;
  background-color: #fff;
}
.gfclassiclist-info.selected{
  background-color: #f1f1f1;
}
.gfclassiclist-right-head{
  text-align: left;
  width: 720px;
  height: 47px;
  background-image: url("/assets/about/aboutInfoHeadBG.png");
  background-repeat: repeat-x;
  font-size: 14px;
  color: #525252;
}
.gfclassiclist-right-head span{
  display: inline-block;
  margin-left: 20px;
  line-height: 2.8;
}
.gfclassiclist-right-info{
  font-size: 14px;
  color: #525252;
  width: 680px;
  margin: 20px auto;
  line-height: 2;
}
.gfclassiclist-right-info span{
  display: inline-block;
}
.gfclassic{
  height: 40px;
  margin-bottom: 10px;
  text-align: left;
}
.gfclassic-title{
  font-size: 16px;
  width: 80%;
  margin-left: 25px;
  /*text-align: left;*/
}
.gfclassic-time{
  /*margin-top: 13px;*/
  text-align: right;
}


  

</style>



        <div class="gfclassiclist-container">
 


          <div class="classic-left-container">
            <div class="left-title">
              <span class="left-CN">经典案例/</span>
              <span class="left-EN">Classic Case</span>
            </div>
            <div><%= image_tag "classic/classic.jpg" %></div>
          </div>


           <div class="gfclassiclist-right-container">
              <div class="gfclassiclist-right-head">
                 <span>首页>经典案例>案例</span>
              </div>
              <div class="gfclassiclist-right-info">
                <div class="gfclassic-list">
                    <% @cases.each do |_case| %>
                      <div class="gfclassic"><!--不用ul li  因为在mac下适配会有字体匹配问题-->
                         <span class="gfclassic-title"><a href="<%= case_path(_case) %>"><%= _case.title %></a></span>
                         <span class="gfclassic-time"><%= _case.created_at.strftime('%Y-%m-%d') %></span>
                      </div>
                    <% end %>
                 </div>

              </div>
              </div>
        </div>

app/views/news/_home_share_list.html.erb
<div class="dynamic-container">
   <div class="container-head">
      <span class="container-head-left">观复动态</span>
      <a href="/news.html"><span class="container-head-right"  id="gotoDynamic">查看更多></span></a>
   </div>
   <div class="dynamic-info">
      <% @newes.each do |news| %>
      <div class="dynamic">
        <a href="<%= news_path(news, format: 'html') %>">
        <span>☆<%= news.title %> </span>
        </a>
      </div>
      <% end %>
   </div>
</div>

app/views/news/index.html.erb
<style type="text/css">

body
{
   text-align: center;
}
.gfdynamiclist-container{
   width: 980px;
   min-height: 530px;
   margin: 30px auto;
   display: inline-block;
}
.gfdynamiclist-left-container{
   width: 240px;
   height: 100%;
   float: left;
}
.gfdynamiclist-right-container{
   width: 720px;
   height: 100%;
   margin-left: 20px;
   background-color: #f1f1f1;
   border-radius: 0 0 10px 10px;
   float: left;
}
.left-title{
   width: 100%;
   height: 40px;
   background-color: #00a0e9;
   color: #fff;
   line-height: 2;
}
.left-title span{
   display: inline-block;
}
.left-CN{
   font-size: 20px;
   padding-left: 20px;
}
.left-EN{
   font-size: 12px;
}
.gfdynamiclist-info{
   width: 100%;
   height: 40px;
   text-align: center;
   font-size: 14px;
   color: #525252;
   line-height: 2.8;
   cursor: pointer;
   background-color: #fff;
}
.gfdynamiclist-info.selected{
   background-color: #f1f1f1;
}
.gfdynamiclist-right-head{
   width: 720px;
   height: 47px;
   background-image: url("/assets/about/aboutInfoHeadBG.png");
   background-repeat: repeat-x;
   font-size: 14px;
   color: #525252;
   text-align: left;
}
.gfdynamiclist-right-head span{
   display: inline-block;
   margin-left: 20px;
   line-height: 2.8;
}
.gfdynamiclist-right-info{
   font-size: 14px;
   color: #525252;
   width: 680px;
   margin: 20px auto;
   line-height: 2;
   text-align: left;
}
.gfdynamiclist-right-info span{
   display: inline-block;
}
.gfdynamic-title{
   font-size: 16px;
   width: 80%;
   margin-left: 25px;
   /*text-align: left;*/
}
.gfdynamic-time{
   margin-top: 13px;
   text-align: right;
}



   
</style>

      <div class="gfdynamiclist-container">
         <div class="gfdynamic-left-container">
            <div class="left-title">
               <span class="left-CN">观复动态/</span>
               <span class="left-EN">Guanfu Dynamic</span>
            </div>
            <div><%= image_tag "about/aboutShadow.png" %></div>
            <div><%= image_tag "about/about.jpg" %></div>
         </div>

         <div class="gfdynamiclist-right-container">
            <div class="gfdynamiclist-right-head">
               <span>首页>观复动态>动态概况</span>
            </div>
            <div class="gfdynamiclist-right-info">
              <div class="gfdynamic-list">

                  <% @newes.each do |news| %>
                  <div class="gfdynamic"><!--不用ul li  因为在mac下适配会有字体匹配问题-->
                     <span class="gfdynamic-title"><a href="<%= news_path(news) %>">☆<%= news.title %></a></span>
                     <span class="gfdynamic-time"><%= news.created_at.strftime('%Y-%m-%d') %></span>
                  </div>
                  <% end %>

               </div>

            </div>
            </div>
         </div>

app/views/welcome/team.html.erb
<style type="text/css">
  
body
{
  text-align: center;
}
.team-container{
  width: 980px;
  height: auto;
  margin: 30px auto;
  display: inline-block;
}
.team-left-container{
  width: 240px;
  height: 100%;
  float: left;
}
.team-right-container{
  width: 720px;
  height: 100%;
  margin-left: 20px;
  background-color: #f1f1f1;
  border-radius: 0 0 10px 10px;
  float: left;
}
.left-title{
  width: 100%;
  height: 40px;
  background-color: #00a0e9;
  color: #fff;
  line-height: 2;
}
.left-title span{
  display: inline-block;
}
.left-CN{
  font-size: 20px;
  padding-left: 20px;
}
.left-EN{
  font-size: 12px;
}
.chief-law{
  width: 100%;
  height: 40px;
  background-color: #f1f1f1;
  text-align: center;
  font-size: 14px;
  color: #525252;
  line-height: 2.8;
  cursor: pointer;
  margin-top: -5px;
}
.team-info{
  width: 100%;
  height: 40px;
  text-align: center;
  font-size: 14px;
  color: #525252;
  line-height: 2.8;
  cursor: pointer;
}
.team-right-head{
  text-align: left;
  width: 720px;
  height: 47px;
  background-image: url("/assets/about/aboutInfoHeadBG.png");
  background-repeat: repeat-x;
  font-size: 14px;
  color: #525252;
}
.team-right-head span{
  display: inline-block;
  margin-left: 20px;
  line-height: 2.8;
}
.team-right-info{
  width: 100%;
}
.right-title{
  font-size: 14px;
  margin-top: 25px;
  margin-left: 20px;
  color: #00a0e9;
  text-align: left;
}
.team-right-line{
  width: 100%;
  height: 1px;
  border-top: 1px solid #b5b5b5;
  margin-top: 5px;
}
.right-lawer-contaner{
  width: 100%;
  height: 250px;
  margin-top: 20px;
  margin-bottom: 29px;
}
.right-lawer-contaner img{
  cursor: pointer;
}
.lawyer-one{
  float: left;
  margin-left: 19px;
}
.lawyer-two{
  float: left;
  margin-left: 27px;
}
.lawyer-three{
  float: left;
  margin-left: 27px;
}
.lawyer-four{
  float: left;
  margin-left: 27px;
}
.lawyer-info{
  margin-top: 8px;
  font-size: 14px;
}
.lawyer-name{
  color: #fa9c1e;
  margin-right: 5px;
}
.lawyer-type{
  margin-top: 0px;
  font-size: 14px;
}
.lawyer-future{
  float: left;
  width: 150px;
  height: 200px;
  background-color: gray;
  text-align: center;
  margin-left: 27px;

}
.lawyer-future span{
  font-size: 14px;
  display: block;
  color: white;
}
.future-info{
  margin-top: 80px;
}  

</style>

 <div class="banner-container">
    <%= image_tag "about/aboutBanner0408.jpg" %>
 </div>
 <div class="banner-yinying" style="margin-top: -45px;">
    <%= image_tag "bannerBottom.png" %>
 </div>

<div class="team-container">
	<div class="team-left-container">
		<div class="left-title">
			<span class="left-CN">专业团队/</span>
			<span class="left-EN">Professional Team</span>
		</div>
		<div><%= image_tag "about/aboutShadow.png" %></div>
		<div class="chief-law">
			<span>专业团队</span>
		</div>
		<div><%= image_tag "about/xuxian.png" %></div>
		<div><%= image_tag "about/about.jpg" %></div>
	</div>
	<div class="team-right-container">
		<div class="team-right-head">
			<span>首页>专业团队</span>
		</div>
		<div class="team-right-info">
			<div id="rightTitle" class="right-title"><span>专业团队</span></div>
      <% 
        @members = Member.where(:level => 1) 
        m_count = @members.count
        t_count = m_count + 1
        _line_count = t_count / 3
        if (t_count%3 == 0)
        else
          _line_count += 1
        end
      %>


      <% _line_count.times do |_line_index| %>

        <div class="team-right-line"></div>

        <div class="right-lawer-contaner">
          <% @members[(_line_index*3)...(_line_index+1)*3].each do |member| %>
          <div class="lawyer-one">
            <div><a href="<%= member_path member %>"><%= image_tag( member.avatar_url, :width => 150, :height => 200 ) %></a></div>
            <div class="lawyer-info"><span class="lawyer-name"><%= member.name %></span><span>  <%= member.position %></span></div>
            <div class="lawyer-type"><span><%= member.title %></span></div>
          </div>
          <% end %>

          <% if _line_index == (_line_count - 1) %>
          <div class="lawyer-future">
            <span class="future-info">观复团队</span>
            <span>等待您的加入</span>
          </div>

          <% end %>
        </div>

      <% end %>
      <div class="team-right-line"></div>
      <div id="rightTitle" class="right-title"><span>高级顾问</span></div>

      <% if false %>
      <div class="right-lawer-contaner">
        <div class="lawyer-one">
          <div><a href="/service.html" ><%= image_tag("team/baowanchao.jpg", width: 150) %></a></div>
          <div class="lawyer-info"><span class="lawyer-name">包万超</span><span>  教授/博士生导师</span></div>
        </div>
      </div>
      <% end %>


      <% 
        @members = Member.where(:level => 2) 
        m_count = @members.count
        t_count = m_count + 1
        _line_count = t_count / 3
        if (t_count%3 == 0)
        else
          _line_count += 1
        end
      %>


      <% _line_count.times do |_line_index| %>

        <div class="team-right-line"></div>

        <div class="right-lawer-contaner">
          <% @members[(_line_index*3)...(_line_index+1)*3].each do |member| %>
          <div class="lawyer-one">
            <div><a href="<%= member_path member %>"><%= image_tag( member.avatar_url, :width => 150, :height => 200 ) %></a></div>
            <div class="lawyer-info"><span class="lawyer-name"><%= member.name %></span><span>  <%= member.position %></span></div>
            <div class="lawyer-type"><span><%= member.title %></span></div>
          </div>
          <% end %>
        </div>

      <% end %>      
		</div>
	</div>
</div>